### PR TITLE
Update the copyright notices

### PR DESCRIPTION
**Pull request by xchs**
Update the copyright notices.

### CODE REVIEW

**Comment by leofeyer** [comment]
Since @fritzmg is maintaining the package, the copyright should probably be:

```
This file is part of the Contao Check.

(c) Fritz Michael Gschwantner
(c) Leo Feyer

@license LGPL-3.0-or-later
```

**Comment by xchs** [comment]
Do you want me to change that? Or are you going to change that yourself?

**Comment by fritzmg** [comment]
@xchs I'd prefer it if you change that :)

**Comment by xchs** [comment]
Okay, I'll do that.

**Comment by xchs** [comment]
@fritzmg All files updated accordingly.

**Pull request merged**
