### PR TITLE
Issue #89: Adding some notes about using git status vs. using the...

### PR DESCRIPTION
**Pull request by ams-tschoening**
…validator of check in a git deployment.

### CODE REVIEW

**Comment by leofeyer** [comment]
I don't see a point in this.

**Comment by tschoening** [comment]
Contao mentions installation using git, the validator of check doesn't seem to work very well in such situations, which I described in issue #89, so I suggest to simply add some notes to not use it and why. I used it, because I was not aware of the limitations in such a deployment and wondered about the results. Even if no one cares about such a use case, form my point of view it shouldn't hurt to mention it. Would have saved me some time in trying to understand how to deal with it because I find check to be very handy.

**Comment by leofeyer** [comment]
If you set up Contao using git, why would you install the check? A simple `git status` will do.

**Comment by tschoening** [comment]
Because check does more than file validation, git doesn't contain all files, e.g. most language files, and there are no limitations documented for check if using git. So I wanted to make sure everything is OK and noticed the limitations of check in such a setup myself. So why not just mention those things beforehand?

**Comment by fritzmg** [comment]
I think it wouldn't hurt to merge at least the first paragraph. However, why do you say

> Therefore validation more or less …

Why is it "more or less"?

**Comment by tschoening** [comment]
> Why is it "more or less"?

Because things can change and the check might be enhanced to e.g. additionally check file permissions. While in such a case it would not check presence and contents of files only anymore, such an additional check wouldn't change anything on the topic and wouldn't need to be mentioned in detail in the docs. Therefore "more or less" to provide some piece of doubt to the reader that there might be more things going on under the hood, which are most likely not that important, though.

If you don't agree just remove those words.

**Comment by fritzmg** [comment]
Closing in favor of #89

**Pull request closed without merging**
