### PR TITLE
add php-intl check (#95)

### PR DESCRIPTION
**Pull request by fritzmg**
This adds an additional check for the PHP Intl Extension (see #95). Again, this PR comes without any translations.

### CODE REVIEW

**Comment by leofeyer** [comment]
I cannot merge the PR like this.

On the start page of the check, only the PHP versions are checked. If you want to check for PHP extensions, you would have to add a details page (as for the file permissions, the repository etc.).

**Comment by fritzmg** [comment]
> It does not have to be added at all IMO.

Well it would be helpful. The following procedure is described quite frequently on the community forum:

1. Users upload the Contao Check to their webspace, where they are told that they can install Contao 4.
2. They download Contao 4 from contao.org and put it on their webspace.
3. They open `/install.php`, enter the Install Tool password and after that are presented with a blank page.
4. Since there is no visible error message, nor will there be an entry in `/app/logs`, they wonder why it's not working.

In most cases it's the missing PHP Intl extension.

**Comment by fritzmg** [comment]
I have created a more detailed PR: #108

**Comment by leofeyer** [comment]
So can this one be closed?

**Comment by fritzmg** [comment]
Yes

**Pull request closed without merging**
