### PR TITLE
Add EOL notice and disallow installation within Contao 4

### PR DESCRIPTION
**Pull request by fritzmg**
See https://github.com/contao/check/issues/150

Screenshot_2019-12-07 Contao Check 12 0(2)

This PR will also disallow the installation within an already present Contao 4 installation.

### CODE REVIEW

**Comment by leofeyer** [comment]
Have you considered removing the installation option altogether?

**Comment by fritzmg** [comment]
Yeah I am actually in favor of that. Anyone who still wants to use the Contao Check to install Contao 3 can still download it from a previous commit.

**Comment by fritzmg** [comment]
Alternative PR: #155

**Comment by fritzmg** [comment]
Closing in favor of #155

**Pull request closed without merging**
