### PR TITLE
change SSL connection check translation (#109)

### PR DESCRIPTION
**Pull request by fritzmg**
See #109

### CODE REVIEW

**Comment by fritzmg** [comment]
Woops, by pushing this translation source, I removed the updated translations from #112 on transifex. 
Not sure how to handle that.

**Comment by leofeyer** [comment]
I would say "your OpenSSL version" instead of "the OpenSSL version".

> Woops, by pushing this translation source, I removed the updated translations from #112 on transifex.
> Not sure how to handle that.

This is a tricky situation. Either you rebase this branch onto the other branch or you only push to Transifex after you have merged the changes into the master branch.

**Comment by fritzmg** [comment]
I see. I'd rather to the latter.

**Comment by fritzmg** [comment]
Updated the PR.

**Pull request merged**
