### PR TITLE
add check for Contao 4.5

### PR DESCRIPTION
**Pull request by fritzmg**
This adds a separate check for Contao 4.5, which checks for PHP `7.1.0` and checks the ICU library version for at least `4.6`.

screenshot-2018-2-8 contao check 12 0

screenshot-2018-2-8 contao check 12 0 1

### CODE REVIEW

**Comment by leofeyer** [comment]
To remain consistency, there should be only one red error message, not a red line and a grey line below.

**Comment by fritzmg** [comment]
> To remain consistency, there should be only one red error message, not a red line and a grey line below.

But that is consistent.

screenshot-2018-2-8 contao check 12 0 2

**Comment by leofeyer** [comment]
Sorry, you are right. I did not recall correctly.

**Comment by fritzmg** [comment]
I have updated the PR. The Contao 4.5 check no inherits from the Contao 4 check.

**Comment by fritzmg** [comment]
@leofeyer what do you think, can this be merged?

**Comment by ausi** [comment]
@fritzmg we should probably update this check because since slug-generator version 1.0.2 [the minimum ICU version is 4.2.1](https://github.com/ausi/slug-generator/blob/v1.0.2/composer.json#L18)

**Pull request merged**
